version: '3'
services:
  pg:
    image: "postgres:12"
    container_name: "hch-listhub-postgres"
    environment:
      POSTGRES_DB: hch-listhub
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./pg/db_data:/var/lib/postgresql/data
