org: sairamtummala
app: realestate
service: listhub-replica

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  iamRoleStatements:
    - Effect: Allow
      Action:
        - 'lambda:InvokeFunction'
        - 'lambda:InvokeAsync'
      Resource: '*'
  region: us-west-2
  environment:
    DB_HOST: ${param:DB_HOST}
    DB_PORT: ${param:DB_PORT}
    DB_NAME: ${param:DB_NAME}
    DB_USER: ${param:DB_USER}
    DB_PASSWORD: ${param:DB_PASSWORD}
    DB_DIALECT: ${param:DB_DIALECT}
  memorySize: 1024
  timeout: 900

functions:
  rateHandler:
    handler: handler.run
    timeout: 900
    events:
      - schedule: rate(1 hour)
  fetchListingsData:
    handler: handler.fetchListingsData
    timeout: 890
    events:
      - schedule: rate(1 hour)
  listhubMonitor:
    handler: handler.listhubMonitor
    timeout: 900
    events:
      - schedule: rate(1 hour)
  streamExecutor:
    handler: handler.streamExecutor
    timeout: 900
  
plugins:
  - serverless-plugin-lambda-insights