org: sairamtummala
app: realestate
service: listhub-replica

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  region: us-west-2
  environment:
    DB_HOST: ${param:DB_HOST}
    DB_PORT: ${param:DB_PORT}
    DB_NAME: ${param:DB_NAME}
    DB_USER: ${param:DB_USER}
    DB_PASSWORD: ${param:DB_PASSWORD}
    DB_DIALECT: ${param:DB_DIALECT}

functions:
  rateHandler:
    handler: handler.run
    events:
      - schedule: rate(1 hour)
  fetchListingsData:
    handler: handler.fetchListingsData
    events:
      - schedule: rate(1 hour)
