org: sairamtummala
app: realestate
service: listhub-replica

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  region: us-west-2
  environment:
    DB_HOST: ${param:DB_HOST}
    DB_PORT: ${param:DB_PORT}
    DB_NAME: ${param:DB_NAME}
    DB_USER: ${param:DB_USER}
    DB_PASSWORD: ${param:DB_PASSWORD}
    DB_DIALECT: ${param:DB_DIALECT}
  memorySize: 1024
  timeout: 900

functions:
  listhubMonitor:
    handler: handler.listhubMonitor
    iamRoleStatementsName: listhubMonitorRole
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - "lambda:InvokeFunction"
          - "lambda:InvokeAsync"
        Resource: '*'
    timeout: 900
    events:
      - schedule: rate(1 hour)

  streamExecutor:
    handler: handler.streamExecutor
    timeout: 890

  monitorSync:
    handler: handler.monitorSync
    timeout: 890
    events:
     # - schedule: rate(5 minutes)

  checkDataInTables:
    handler: handler.checkDataInTables
    timeout: 890

  prepareListhubTables:
    handler: handler.prepareListhubTables
    timeout: 890
  
plugins:
  - serverless-plugin-lambda-insights
  - serverless-iam-roles-per-function