org: sairamtummala
app: realestate
service: listhub-replica

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  region: us-west-2
  environment:
    DB_HOST: ${param:DB_HOST}
    DB_PORT: ${param:DB_PORT}
    DB_NAME: ${param:DB_NAME}
    DB_USER: ${param:DB_USER}
    DB_PASSWORD: ${param:DB_PASSWORD}
    DB_DIALECT: ${param:DB_DIALECT}
    LISTHUB_CLIENT_ID: ${param:LISTHUB_CLIENT_ID}
    LISTHUB_CLIENT_SECRET: ${param:LISTHUB_CLIENT_SECRET}
    LISTHUB_OAUTH2_TOKEN_API: ${param:LISTHUB_OAUTH2_TOKEN_API}
    LISTHUB_META_API: ${param:LISTHUB_META_API}
    LISTHUB_REPLICATION_API: ${param:LISTHUB_REPLICATION_API}
  memorySize: 4024
  timeout: 900

functions:
  listhubMonitor:
    handler: handler.listhubMonitor
    iamRoleStatementsName: listhubMonitorRole
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - "lambda:InvokeFunction"
          - "lambda:InvokeAsync"
        Resource: '*'
    timeout: 900
    # events:
    #   - schedule: rate(1 hour)

  streamExecutor:
    handler: handler.streamExecutor
    timeout: 890
    reservedConcurrency: 10

    deadLetter:
      sqs: streamExecutor-dl-queue

  monitorSync:
    handler: handler.monitorSync
    timeout: 890
    events:
     - schedule: rate(5 minutes)

  prepareListhubTables:
    handler: handler.prepareListhubTables
    timeout: 890
  
plugins:
  - serverless-plugin-lambda-insights
  - serverless-iam-roles-per-function
  - serverless-plugin-lambda-dead-letter