module.exports = {
    metaURL: "http://api.listhub.com/public_sandbox/replication/metadata",
    replicationURL: "http://api.listhub.com/public_sandbox/replication/query",
    token: "eyJraWQiOiI1c0RNZ1dhbDlSUXFyLTJDNVRmNVFES3I3MGZSMXM3a202X1FzUUxWb2w4IiwiYWxnIjoiUFMyNTYifQ.eyJ1c2VyIjp7ImNsaWVudElkIjoicmVkZWZ5cmVuIiwiY2hhbm5lbElkIjo1MDh9LCJzdWIiOiJyZWRlZnlyZW4iLCJhdWQiOiJhcGkubGlzdGh1Yi5jb20iLCJpc3MiOiJ0cnVzcy5saXN0aHViLm1vdmVhd3MuY29tIiwiaWF0IjoxNjE4NTcwOTcwLCJleHAiOjE2MTg2NTczNzB9.WLiOVkeKPr_rvXLEmeItXjHUGM2PPd5nLBGhVEBBcZEXMpJXqfv003R1URnRLHWiFgeQBbBOSbpwOZBijMXY9LvmQN4hXtCBZPJxxW_ER619rqJBofON2c0l9QmLLb4VdgjP16mJT0EptYhnWg3QKulhpBWD42q9u-nPlJI02Y07XxwIo8SysDKFnXmy0I-mRkXOpcU8OwAJV3aZG4_9V85Szyh2s44tama1Tq9zcutwidabpbxXOgC4VTFhlg-uU42mKhLAHEZ4-kTxcGLnUz7h9aU5I873oIUNY7EmgbKpbrhUYTSl6MAnAViSpNBiJTHnfVFGvBj-gGz3ChbzRQ"
  };

  // http://api.listhub.com/public_sandbox
  // https://api.listhub.com/replication/query